// js/apps-data.js

const appsData = [
    // Slider Apps (مميزة)
    { id: 1, name: "Netflix", rating: 4.8, downloadLink: "#", isSlider: true, category: "Entertainment" },
    { id: 2, name: "FIFA Mobile", rating: 4.9, downloadLink: "#", isSlider: true, category: "Games" },
    { id: 3, name: "PUBG Mobile", rating: 4.7, downloadLink: "#", isSlider: true, category: "Games" },
    
    // Regular Apps (41 تطبيق إضافي ليصل المجموع لـ 44)
    { id: 4, name: "WhatsApp", rating: 4.5, downloadLink: "#", isSlider: false, category: "Social" },
    { id: 5, name: "Instagram", rating: 4.6, downloadLink: "#", isSlider: false, category: "Social" },
    { id: 6, name: "TikTok", rating: 4.4, downloadLink: "#", isSlider: false, category: "Social" },
    { id: 7, name: "Telegram", rating: 4.7, downloadLink: "#", isSlider: false, category: "Social" },
    { id: 8, name: "Snapchat", rating: 4.3, downloadLink: "#", isSlider: false, category: "Social" },
    { id: 9, name: "Spotify", rating: 4.8, downloadLink: "#", isSlider: false, category: "Music" },
    { id: 10, name: "YouTube Music", rating: 4.5, downloadLink: "#", isSlider: false, category: "Music" },
    { id: 11, name: "Free Fire", rating: 4.6, downloadLink: "#", isSlider: false, category: "Games" },
    { id: 12, name: "Call of Duty", rating: 4.7, downloadLink: "#", isSlider: false, category: "Games" },
    { id: 13, name: "Clash of Clans", rating: 4.8, downloadLink: "#", isSlider: false, category: "Games" },
    { id: 14, name: "Roblox", rating: 4.5, downloadLink: "#", isSlider: false, category: "Games" },
    { id: 15, name: "Minecraft", rating: 4.9, downloadLink: "#", isSlider: false, category: "Games" },
    { id: 16, name: "Uber", rating: 4.4, downloadLink: "#", isSlider: false, category: "Lifestyle" },
    { id: 17, name: "Booking.com", rating: 4.6, downloadLink: "#", isSlider: false, category: "Travel" },
    { id: 18, name: "Airbnb", rating: 4.7, downloadLink: "#", isSlider: false, category: "Travel" },
    { id: 19, name: "Google Maps", rating: 4.8, downloadLink: "#", isSlider: false, category: "Navigation" },
    { id: 20, name: "Waze", rating: 4.6, downloadLink: "#", isSlider: false, category: "Navigation" },
    { id: 21, name: "Amazon", rating: 4.5, downloadLink: "#", isSlider: false, category: "Shopping" },
    { id: 22, name: "AliExpress", rating: 4.4, downloadLink: "#", isSlider: false, category: "Shopping" },
    { id: 23, name: "Shein", rating: 4.6, downloadLink: "#", isSlider: false, category: "Shopping" },
    { id: 24, name: "Canva", rating: 4.8, downloadLink: "#", isSlider: false, category: "Productivity" },
    { id: 25, name: "Adobe Lightroom", rating: 4.7, downloadLink: "#", isSlider: false, category: "Photography" },
    { id: 26, name: "VSCO", rating: 4.5, downloadLink: "#", isSlider: false, category: "Photography" },
    { id: 27, name: "CapCut", rating: 4.8, downloadLink: "#", isSlider: false, category: "Video" },
    { id: 28, name: "InShot", rating: 4.6, downloadLink: "#", isSlider: false, category: "Video" },
    { id: 29, name: "Duolingo", rating: 4.9, downloadLink: "#", isSlider: false, category: "Education" },
    { id: 30, name: "Coursera", rating: 4.7, downloadLink: "#", isSlider: false, category: "Education" },
    { id: 31, name: "Khan Academy", rating: 4.8, downloadLink: "#", isSlider: false, category: "Education" },
    { id: 32, name: "Zoom", rating: 4.4, downloadLink: "#", isSlider: false, category: "Business" },
    { id: 33, name: "Microsoft Teams", rating: 4.3, downloadLink: "#", isSlider: false, category: "Business" },
    { id: 34, name: "Slack", rating: 4.6, downloadLink: "#", isSlider: false, category: "Business" },
    { id: 35, name: "Twitch", rating: 4.5, downloadLink: "#", isSlider: false, category: "Streaming" },
    { id: 36, name: "Discord", rating: 4.7, downloadLink: "#", isSlider: false, category: "Social" },
    { id: 37, name: "Reddit", rating: 4.4, downloadLink: "#", isSlider: false, category: "News" },
    { id: 38, name: "Twitter", rating: 4.2, downloadLink: "#", isSlider: false, category: "Social" },
    { id: 39, name: "Facebook", rating: 4.1, downloadLink: "#", isSlider: false, category: "Social" },
    { id: 40, name: "Pinterest", rating: 4.6, downloadLink: "#", isSlider: false, category: "Social" },
    { id: 41, name: "LinkedIn", rating: 4.5, downloadLink: "#", isSlider: false, category: "Business" },
    { id: 42, name: "PayPal", rating: 4.7, downloadLink: "#", isSlider: false, category: "Finance" },
    { id: 43, name: "Binance", rating: 4.6, downloadLink: "#", isSlider: false, category: "Finance" },
    { id: 44, name: "Coinbase", rating: 4.5, downloadLink: "#", isSlider: false, category: "Finance" }
];
